// Generated by Copilot
"use client"

import { useState } from "react"
import Navbar from "@/components/Navbar"
import GuestDetailsStep from "@/components/booking/guest-details-step"
import { BookingData } from "../page"

export default function GuestDetailsPage() {
  const [bookingData, setBookingData] = useState<BookingData>({
    checkIn: "",
    checkOut: "",
    guests: 1,
    roomType: ""
  })
  const [error, setError] = useState("")
  const [isLoading, setIsLoading] = useState(false)

  const handleUpdate = (data: Partial<BookingData>) => {
    setBookingData(prev => ({ ...prev, ...data }))
  }

  const handleNext = () => {
    // Navigate to payment step
  }

  const handlePrev = () => {
    // Navigate back
    window.history.back()
  }

  return (
    <div className="min-h-screen bg-neutral pt-23">
      <Navbar />
      <div className="container mx-auto px-4 py-20">
        {error && (
          <div className="mb-6 p-4 bg-error/10 border border-error/20 rounded-md">
            <p className="text-error text-sm">{error}</p>
          </div>
        )}

        <GuestDetailsStep
          data={bookingData}
          onUpdate={handleUpdate}
          onNext={handleNext}
          onPrev={handlePrev}
          setError={setError}
          setIsLoading={setIsLoading}
        />
      </div>
    </div>
  )
}
